name: FullyParallel
jobs:
  ui-test-b:
    time: 23
    runs-on: ios
    needs: []

  unit-test-b:
    time: 17
    runs-on: ios
    needs: []

  snapshot-test-b:
    time: 14
    runs-on: ios
    needs: []

  ui-test-a:
    time: 23
    runs-on: ios
    needs: []

  unit-test-a:
    time: 17
    runs-on: ios
    needs: []

  snapshot-test-a:
    time: 14
    runs-on: ios
    needs: []

  modules:
    time: 18
    runs-on: ios
    needs: []

  quality:
    time: 6
    runs-on: linux
    needs: [modules, snapshot-test-a, unit-test-a, ui-test-a, snapshot-test-b, unit-test-b, ui-test-b]

  reporting:
    time: 1
    runs-on: linux
    needs: [quality]
