name: TenantSeparatelyAndTest
jobs:
  build-a:
    time: 21
    runs-on: ios
    needs: []

  build-b:
    time: 21
    runs-on: ios
    needs: []

  ui-test-b:
    time: 13
    runs-on: ios
    needs: [build-a, build-b]

  unit-test-b:
    time: 7
    runs-on: ios
    needs: [build-a, build-b]

  snapshot-test-b:
    time: 8
    runs-on: ios
    needs: [build-a, build-b]

  ui-test-a:
    time: 13
    runs-on: ios
    needs: [build-a, build-b]

  unit-test-a:
    time: 7
    runs-on: ios
    needs: [build-a, build-b]

  snapshot-test-a:
    time: 8
    runs-on: ios
    needs: [build-a, build-b]

  modules:
    time: 18
    runs-on: ios
    needs: []

  quality:
    time: 6
    runs-on: linux
    needs: [ modules, snapshot-test-a, unit-test-a, ui-test-a, snapshot-test-b, unit-test-b, ui-test-b ]

  reporting:
    time: 1
    runs-on: linux
    needs: [ quality ]
